name: Scrape Steam Profile and Publish Worker

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - name: create env file
        run: |
          touch .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
      - name: build and run scraper
        run: |
          pnpm run build
          pnpm run scrape
      - uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: db

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    name: Deploy API
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - uses: actions/download-artifact@v3
        with:
          name: scraped-data
          path: db
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: src/api
          command: publish --env production
